services:
  Auth.Jwt:
    class: ../services/Auth0TokenService

  Auth.UserAuthenticator:
    class: ../../domain/UserAuthenticator
    arguments: ["@Auth.Jwt"]

  Auth.UserRepository:
    class: ../repositories/InMemoryUserRepository

  Auth.UserSearcher:
    class: ../../domain/UserSearcher
    arguments: ["@Auth.UserRepository"]

  Auth.UserCreator:
    class: ../../domain/UserCreator
    arguments: ["@Auth.UserRepository"]

  Auth.UserFinder:
    class: ../../domain/UserFinder
    arguments: ["@Auth.UserRepository"]

  Auth.application.CreateUser:
    class: ../../application/CreateUser
    arguments: ["@Auth.UserCreator"]

  Auth.application.FindUser:
    class: ../../application/FindUser
    arguments: ["@Auth.UserFinder"]

  Auth.application.Login:
    class: ../../application/Login
    arguments: ["@Auth.UserSearcher", "@Auth.UserAuthenticator"]

  Auth.controller.CreateUser:
    class: ../controllers/CreateUserController
    arguments: ["@Auth.application.CreateUser"]

  Auth.controller.FindUser:
    class: ../controllers/FindUserController
    arguments: ["@Auth.application.FindUser"]

  Auth.controller.Login:
    class: ../controllers/LoginController
    arguments: ["@Auth.application.Login"]
