name: CI

on:
  pull_request:
    paths-ignore:
      - "**.md"
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - "main"
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test
